language: node_js
node_js:
  - "6"
dist: trusty
sudo: required
services: mongodb
before_script:
  - sudo apt-get install sudo
  - mongo usersDB --eval 'db.users.insert({"email":"gianluca.cornetta@gmail.com","firstname":"Gianluca","hash":"9b8e750b79b628ad5a1a1393d48cf70eb21f9250005c72db6a29f8ca60df818b819fff45e909e3e175264a88f60d8f7d9b12348bd312e6222225e9dce11c259f","issuperuser":true,"lastlogged":ISODate("2018-04-11T03:10:39.150Z"),"lastname":"Cornetta","pathtophoto":"/uploads/img/57a491c2c46763f60bf25acd.png","salt":"f6c7b8dda883b7781503c6cfe733ba4b","username":"gcornetta" });'
  - mongo usersDB --eval 'db.machines.insert({"adcDevice":[{"device":"ADS 1115","vendor":"Texas Instruments","_id":ObjectId("5adfd565b2db9f093d7a0de0")}],"baudRate":115200,"defaultValues":{"type":"flat","yz":"on","xz":"on","topIntensity":1,"topZ":0,"bottomIntensity":0,"bottomZ":-10,"sequence":-1,"order":-1,"merge":1.5,"threshold":0.5,"offsets":4,"cutDepth":0.1,"direction":"climb","switchSort":"on","thickness":1.7,"overlap":50,"error":1.1,"diameter":0.4,"speed":4,"zhome":60.5,"yhome":152.4,"xhome":0,"zjog":12,"z":10,"y":10,"x":10,"machines":"srm_20"},"deviceUri":"serial:/dev/ttyS0?baud=115200","dutyCycle":10,"hysteresis":100,"isConfigured":true,"name":"testMachine","queuedJobs":[ ],"sampleTime":100,"threshCurr":1000,"type":"Milling machine","vendor":"Roland"});'
script: "sudo npm test"

